### ISSUE TITLE
Server crashes when friend joins

### ISSUE THREAD

**Issue by bushmaster75** [LiviiYS/Euphoric_Curiosity#14]
I host my server using the '/publish [port]' command. My friend joined and was able to choose a race and begin playing. Any time he rejoins the server after that, the server saves and closes, and my game with it. We've been able to recreate the crash multiple times consistently, and it happens shortly after he joins.

[11:43:51] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Duplicate registration for ae2:qnb
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.4) ~[?:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreens.register(HandledScreens:76) ~[?:?]
	at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:66) ~[fabric-screen-handler-api-v1-1.1+3ac43d95c8-929ee692471d6200.jar:?]
	at appeng.init.client.InitScreens.register(InitScreens.java:198) ~[appliedenergistics2-10.0.0-alpha.6.jar:?]
	at appeng.init.client.InitScreens.init(InitScreens.java:121) ~[appliedenergistics2-10.0.0-alpha.6.jar:?]
	at appeng.core.AppEngClient.postClientSetup(AppEngClient.java:204) ~[appliedenergistics2-10.0.0-alpha.6.jar:?]
	at appeng.core.AppEngClient.clientSetup(AppEngClient.java:177) ~[appliedenergistics2-10.0.0-alpha.6.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-1.4.1+c15ca335c8-83bdf7047940da8a.jar:?]
	at net.minecraft.client.MinecraftClient.handler$cab000$onStart(MinecraftClient:9508) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:712) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37) ~[notenoughcrashes-4.1.3+1.18-fabric.jar:?]
	at net.minecraft.client.MinecraftClient.modify$egi000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:17546) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:43:51] [Render thread/INFO]: Stopping!
[11:43:51] [CullThread/INFO]: [STDOUT]: Shutting down culling task!
[11:43:51] [Render thread/INFO]: closing rrp modern_industrialization:general
[11:43:51] [Render thread/INFO]: closing rrp minecraft:extrasounds
Process exited with code 0.

**Comment by LiviiYS** [comment]
Please use latest, should be fixed
