### ISSUE TITLE
Server crash for Version 0.5

### ISSUE THREAD

**Issue by Sound311** [LiviiYS/Euphoric_Curiosity#17]
tired to start server. 

**Mod"owo-lib" is the wrong version:**
[main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
- Replace mod 'o?o' (owo) 0.3.7+1.18 with version 0.3.8+1.18 or later.
Unmet dependency listing:
- Mod 'Alloy Forgery' (alloy_forgery) 2.0.8+1.18 requires version 0.3.8 or later of mod 'o?o' (owo), but only the wrong version is present: 0.3.7+1.18!
- Mod 'o?o' (owo) 0.3.7+1.18 is being provided through e.g. \mods\mythicmetals-0.11.0.jar -> META-INF/jars/owo-lib-0.3.7+1.18.jar
- Mod 'Conjuring' (conjuring) 1.0.17+1.18 requires version 0.3.8+1.18 or later of mod 'o?o' (owo), but only the wrong version is present: 0.3.7+1.18!
- Mod 'o?o' (owo) 0.3.7+1.18 is being provided through e.g. \mods\mythicmetals-0.11.0.jar -> META-INF/jars/owo-lib-0.3.7+1.18.jar

**After i tired to change the version myself, following error occurs:**
[main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mythicmetals'!
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.11) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
        at net.minecraft.server.Main.main(Main:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
        at nourl.mythicmetals.item.MythicItemGroups.setup(MythicItemGroups.java:28) ~[mythicmetals-0.11.0.jar:?]
        at io.wispforest.owo.itemgroup.OwoItemGroup.initialize(OwoItemGroup.java:75) ~[owo-lib-0.3.10+1.18.jar:?]
        at nourl.mythicmetals.MythicMetals.onInitialize(MythicMetals.java:41) ~[mythicmetals-0.11.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at nourl.mythicmetals.item.MythicItemGroups.setup(MythicItemGroups.java:28) ~[mythicmetals-0.11.0.jar:?]
        at io.wispforest.owo.itemgroup.OwoItemGroup.initialize(OwoItemGroup.java:75) ~[owo-lib-0.3.10+1.18.jar:?]
        at nourl.mythicmetals.MythicMetals.onInitialize(MythicMetals.java:41) ~[mythicmetals-0.11.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
        ... 15 more

**Comment by LiviiYS** [comment]
Please redownload

**Comment by Smakthatwaffle** [comment]
Im getting the same error. Im downloading the updated server files.

**Comment by Sound311** [comment]
> Please redownload

After fresh download and install same error occurs

**Comment by Sound311** [comment]
copied mods, config and kubejs from the client version to the server, after that the server works.

**Comment by LiviiYS** [comment]
Fixed in 0.5B

**Comment by Sound311** [comment]
[14:53:58] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Modern Industrialization' (modern_industrialization) 1.0.0 (\mods\Modern-Industrialization-1.0.0.jar) with any version that is compatible with:
Unmet dependency listing:
         - Mod 'Modern Industrialization' (modern_industrialization) 1.0.0 requires any version of roughlyenoughitems, which is missing!
