### ISSUE TITLE
Server install issue

### ISSUE THREAD

**Issue by WARPAKS** [LiviiYS/Euphoric_Curiosity#44]
After installing server, at first launch i get an error from fabric loader: Uncaught exception in thread main.

 Here is the content of the error:

java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: java.lang.RuntimeException: Error invoking MC server bundler: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.processBundlerJar(MinecraftGameProvider.java:321)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:206)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:172)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	... 5 more
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider$1.loadClass(MinecraftGameProvider.java:277)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.processBundlerJar(MinecraftGameProvider.java:297)
	... 10 more

Thx for any help.

**Comment by LiviiYS** [comment]
The Java version is outdated.
What version are you using?

**Comment by LiviiYS** [comment]
All 1.18.1 versions of the Modpack need java 17 to run

**Comment by WARPAKS** [comment]
> All 1.18.1 versions of the Modpack need java 17 to run

Oh good to know. Thanks a lot.
