### ISSUE TITLE
 Applied Energistics 2 crashing game

### ISSUE THREAD

**Issue by jtoo12** [LiviiYS/Euphoric_Curiosity#90]
hello i crashed when I made a charger from applied energetics and now cant load into the server i played on that i made it on. the crash report says. i have been trying to reconnect with not success and just crash the second i join and cannot do anything 

Time: 2023-01-07 16:56:55
Description: Unexpected error

java.lang.NoClassDefFoundError: appeng/block/grindstone/CrankBlock
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28)
	at mod.crend.dynamiccrosshair.compat.appliedenergistics.AE2Handler.checkBlockInteractable(AE2Handler.java:192)
	at mod.crend.dynamiccrosshair.compat.appliedenergistics.ApiImplAppliedEnergistics2.checkBlockInteractable(ApiImplAppliedEnergistics2.java:32)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.isBlockInteractable(CrosshairHandler.java:156)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:207)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:262)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:283)
	at net.minecraft.client.gui.hud.InGameHud.handler$cnm000$dynamiccrosshair$tickDynamicCrosshair(InGameHud:17042)
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud:1305)
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud:1271)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1792)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1135)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: appeng.block.grindstone.CrankBlock
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mod.crend.dynamiccrosshair.compat.appliedenergistics.AE2Handler.checkBlockInteractable(AE2Handler.java:192)
	at mod.crend.dynamiccrosshair.compat.appliedenergistics.ApiImplAppliedEnergistics2.checkBlockInteractable(ApiImplAppliedEnergistics2.java:32)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.isBlockInteractable(CrosshairHandler.java:156)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:207)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:262)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:283)
	at net.minecraft.class_329.handler$cnm000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:17042)
	at net.minecraft.class_329.method_1748(class_329.java:1305)
	at net.minecraft.class_329.method_39191(class_329.java:1271)
Mixins in Stacktrace: None found

-- Affected level --
Details:
	All players: 1 total; [class_746['JTOO12'/367472, l='ClientLevel', x=3005.58, y=72.00, z=-7585.10]]
	Chunk stats: 1024, 461
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,63,0), Section: (at 0,15,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 25830049 game time, 23450167 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace: None found

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, loadmyresources.hiddenpack

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 651844608 bytes (621 MiB) / 2357198848 bytes (2248 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=15.39.56.845
	Graphics card #1 name: AMD Radeon RX 6750 XT
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x73df
	Graphics card #1 versionInfo: DriverVersion=31.0.12029.10015
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.00
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.00
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37557.58
	Virtual memory used (MB): 21006.52
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 101.01
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advanced-tooltips: Advanced Tooltips 1.6.0+1.19
			advanced-tooltips-core: Advanced Tooltips Core 1.6.0
		advdebug: Advancements Debug 2.3.0
		ae2: Applied Energistics 2 12.9.2
			noindium: No Indium? 1.1.0+1.19
		ae2wtlib: AE2WTLib 12.8.4
		almostunified: AlmostUnified 1.19.2-0.2.2
		alternate-current: Alternate Current 1.4.0
		amecs: Amecs 1.3.8+mc.1.19-rc2
			amecsapi: Amecs API 1.3.6+mc22w17a
		amphitritecoffer: Amphitrite Coffer 1.2.2
		anakus_status_bars: Anaku's Status Bars 1.1.8-1.19.2
		architectury: Architectury 6.3.49
		artifacts: Artifacts 7.1.1+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 17.1.3
		audio_engine_tweaks: Tweaks for Audio Engine 1.2.3
		auditory: Auditory 0.0.4-1.19.x
		awesomedungeonend: Awesome dungeon the end 3.0.0
		awesomedungeonnether: Awesome dungeon nether 3.0.0
		backportgamerules: Backport Gamerules 1.0.1+1.19.2
		badpackets: Bad Packets 0.2.0
		badstdout: BadStdOut 1.1.1-1.19
		balm-fabric: Balm 4.5.2+0
		bclib: BCLib 2.1.2
		betteranimationscollection: Better Animations Collection 4.0.4
		bettercombat: Better Combat 1.4.5+1.19
		bettercontrols: Better Controls 1.2.3
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.1
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.1
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		bhmenu: BHMenu-Fabric 1.19-1.3
		bookshelf: Bookshelf 16.1.11
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.3-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bushierflowers: Bushier Flowers 0.0.1-1.19.2
		cameraoverhaul: Camera Overhaul 1.3.1-fabric-universal
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		clear-skies: Clear Skies 2.0.95
		clienttweaks: Client Tweaks 8.1.0
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		combatroll: Combat Roll 1.0.8+1.19
		comforts: Comforts 6.0.2+1.19.2
			spectrelib: SpectreLib 0.10.0+1.19
		completeconfig: CompleteConfig 2.0.0
			coat: Coat 1.0.0-beta.17+mc22w17a
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		computercraft: CC: Restitched 1.101.2
			io_netty_netty-codec-http: netty-codec-http 4.1.77.Final
			org_squiddev_cobalt: Cobalt 0.5.5
		conjuring: Conjuring 1.0.25+1.19
		controlling: Controlling For Fabric 10.0+7
		cookingforblockheads: Cooking for Blockheads 13.3.0
		couplings: Couplings 1.9.1+1.19
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		croptopia: Croptopia 2.1.2
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cull-less-leaves: Cull Less Leaves 1.0.6
			conditional-mixin: conditional mixin 0.3.0
		cullclouds: Cull Clouds 0.1.0
		debugify: Debugify 2.8.0
			com_github_llamalad7_mixinextras: mixinextras 0.1.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		do_a_barrel_roll: Do a Barrel Roll 2.2.1+1.19.2
		dragonloot: DragonLoot 1.1.2
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.3.3
		dungeon_difficulty: Dungeon Difficulty 1.1.1+1.19
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.0.2
		dungeons_arise: When Dungeons Arise 2.1.51
		dungeonvanilla: Dungeon vanilla clusters plus 3.0.0
		dynamiccrosshair: Dynamic Crosshair 3.11+1.19.2
		dynamiccrosshaircompat: Dynamic Crosshair Compat 1.11+1.19.2
		edenring: EdenRing 0.6.4
		elden_horses: Elden Horses 1.0.1+1.19.2
		enchdesc: EnchantmentDescriptions 13.0.8
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entity-view-distance: Entity View Distance 1.0.2+1.19
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		exordium: Exordium 1.0.1-mc1.19.2
		experiencebugfix: Experience Bug Fix 18
		extragenerators: Extra Generators 1.2.1-BETA+1.19
			team_reborn_energy: Energy 2.2.0
		extraorigins: Extra Origins 1.19-2
		fabric-api: Fabric API 0.71.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.14+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.10+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.31+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.5+2d2baf4b90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.4+4d0d570390
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-furnaces: Fabric Furnaces 2.2.0-1.19.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricenchantments: Fabric Enchantments 0.8.1
		fabricloader: Fabric Loader 0.14.10
		fabricshieldlib: Fabric Shield Lib 1.6.0-1.19
			mm: Manningham Mills 2.3
		fancymenu: FancyMenu 2.12.6
		farmingforblockheads: Farming for Blockheads 11.1.0
		faster_entity_animations: FastAnim 1.5.6
		fastload: Fast Load 1.2.1
		ferritecore: FerriteCore 4.2.1
		feytweaks: FeyTweaks 1.19-1.2.3
		ftbchunks: FTB Chunks 1902.3.9-build.168
		ftblibrary: FTB Library 1902.3.9-build.144
		ftbteams: FTB Teams 1902.2.9-build.61
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		gearreborn: Gear Reborn 1.19-0.1.15
		geckolib3: Geckolib 3.1.35
			com_eliotlash_mclib_mclib: mclib 19
		go-fish: Go Fish 1.6.0-1.19.1
		goldensteak: Goldensteak 1.0.5-1.19
		graveyard: The Graveyard 2.1
		halfdoors: Half Doors 1.3.9+1.19.x
		harvest_scythes: Harvest Scythes 2.5.4+mc1.19.2
		healthoverlay: Health Overlay 7.1.1
			fiber: fiber 0.23.0-2
		holdthatchunk: Hold That Chunk 2.0.1
		hookshot: Hookshot 26.0
		icarus: Icarus 1.13
		immediatelyfast: ImmediatelyFast 1.0.4
		indium: Indium 1.0.9+mc1.19.2
		indrev: Industrial Revolution 1.15.1-BETA
			fake-player-api: Fake Player API 0.4.0
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		indrev-nikolite: Industrial Revolution: Nikolite Expansion 1.0+1.19.2
		inmis: Inmis 2.7.1-1.19
		inmisaddon: InmisAddon 1.0.2
		inventoryessentials: Inventory Essentials 5.0.0
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		iris: Iris 1.4.0
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		ironchests: Iron Chests: Restocked 3.0.2
		java: OpenJDK 64-Bit Server VM 17
		keebsz: Keebsz's Battle Towers 0.4.0
		kibe: Kibe 1.9.10-BETA+1.19
			playerabilitylib: Pal 1.6.0
		konkrete: Konkrete 1.5.3
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn fabric-1.0.2
		libra: Libra 0.5.44
		libraryferret: Library ferret 3.0.0
		lightestlamp: Lightest Lamps 3.0.0f
		limitedchunks: Limited Chunkloading Mod 1.19.2-2.6
		lithium: Lithium 0.10.1
		loadmyresources: Load My Resources 1.0.1
		logbegone: Log Begone 1.0.2
		lootr: Lootr 0.4.22.61
		lucium: Lucium 1.1
			lib39-core: Lib39 (Core) 1.1.10
		maxenchantx: Max Enchant X 1.1-1.19.1
		maxhealthfix: MaxHealthFix 8.0.1
		mcda: MC Dungeons Armors 2.2.0
		mcdw: MC Dungeons Weapons 5.0.4-1.19
			enchant_giver: Enchant Giver 1.3.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		mcpitanlibarch: MCPitanLibarch 1.1.2-1.19-fabric
		megane: megane 8.3.0
			megane-api: megane-api 8.3.0
			megane-applied-energistics-2: megane-applied-energistics-2 8.3.0
			megane-extra-generators: megane-extra-generators 8.3.0
			megane-fabric-transfer: megane-fabric-transfer 8.3.0
			megane-industrial-revolution: megane-industrial-revolution 8.3.0
			megane-kibe: megane-kibe 8.3.0
			megane-reborn-core: megane-reborn-core 8.3.0
			megane-reborn-energy: megane-reborn-energy 8.3.0
			megane-runtime: megane-runtime 8.3.0
			megane-tech-reborn: megane-tech-reborn 8.3.0
			megane-vanilla: megane-vanilla 8.3.0
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		mixintrace: MixinTrace 1.1.1+1.17
		moderate-loading-screen: Mod-erate Loading Screen 1.1.3+1.19
		modern_industrialization: Modern Industrialization 1.3.2
			magna: Magna 1.8.0-1.19
		modmenu: Mod Menu 4.1.0
		moreculling: More Culling 1.19.1-0.10.0
		moredoors: More Doors 1.0.0
		moreleads: Moreleads 1.19.2-1.0.0
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		netherportalfix: NetherPortalFix 10.0.0
		nochatreports: No Chat Reports 1.19.2-v1.13.11
		notenoughcrashes: Not Enough Crashes 4.1.8+1.19.2
		nounusedchunks: No Unused Chunks 1.3
		numismatic-overhaul: Numismatic Overhaul 0.2.4+1.19
			stacc: Stacc 1.3.3
		omnihopper: Omni-Hopper 1.1.3+1.19
			cooldown-coordinator: Cooldown Coordinator 0.4.2
		openloader: OpenLoader 15.0.1
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				calio: Calio 1.7.0
		origins-classes: Origins: Classes 1.4.0
		originsideologies: Origins: Ideologies 1.0
		originsumbrellas: Origins: Umbrellas 1.5.4
		owo: oωo 0.8.5+1.19
			blue_endless_jankson: jankson 1.2.1
		paradise_lost: Paradise Lost 0.2.0-beta+1.19
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.7.1
			moretags: More Tags 3.0.5
		patchouli: Patchouli 1.19.2-77-FABRIC
		pehkui: Pehkui 3.6.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		peripheralium: Peripheralium 0.4.3-1.19.2
		philipsruins: Philip`s ruins 1.19.2
		player-animator: Player Animator 0.4.0-test1
		polymorph: Polymorph 0.45.0+1.19.2
		projectiledamage: Projectile Damage Attribute 2.2.0+1.19
		puzzleslib: Puzzles Lib 4.3.12
		qolfixes: QoLFixes 2.0.2-1.19
		reborncore: Reborn Core 5.3.4
		recipecache: recipecache 0.2.0-1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		revelationary: Revelationary 1.0.2
		rhino: Rhino 1902.2.1-build.257
		ringsofascension: Rings of Ascension 1.0
		roughlyenoughitems: Roughly Enough Items 9.1.565
			error_notifier: Error Notifier 1.0.9
		shinyhorses: Shiny Horses 1.0.0
		shouldersurfing: Shoulder Surfing Reloaded 2.2.16
		skyvillages: Sky Villages 1.0.2.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.11+mc1.19.2-build.68
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		solid_mobs: Solid Mobs 1.5
		spark: spark 1.9.45
		spectrum: Spectrum 1.5.7-1.19.2-magic
			additionalentityattributes: Additionalentityattributes 1.0.0+1.19
			programmerartinjector: Programmer Art Injector 1.2.1
			satin: Satin 1.9.0
		sprintometer: Sprint O' Meter 2.0a
		starlight: Starlight 1.1.1+fabric.ae22326
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		techreborn: Tech Reborn 5.3.4
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		things: Things 0.2.20+1.19
		thorium: thorium 1.3.2
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
		tlc: The Lost Castle 1.0.0
		tooltipfix: ToolTip Fix 1.1.0-1.19
		tooltiptweaks: Tooltip Tweaks 1.1.0
		tr-patchouli: Tech Reborn Patchouli 2.1.1
		trashslot: TrashSlot 12.0.1
		treeaxe: The TreeAxe 1.2.24
			pugh_tools: Pugh Tools 1.3.23
		trinkets: Trinkets 3.4.0
		trulytreasures: Truly Treasures 1.19-2.0.2
		turtlematic: Turtlematic 0.5.0
		twilightforest: The Twilight Forest 4.2.301
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forgeconfigapiport: Forge Config API Port 4.1.4
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			serialization_hooks: Serialization Hooks 0.3.22
			template: TEMPLATE 2.0.547+1.19.2
				porting_lib_base: Porting Lib Base 2.0.547+1.19.2
				porting_lib_entity: Porting Lib Entity 2.0.547+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.0.547+1.19.2
				porting_lib_models: Porting Lib Models 2.0.547+1.19.2
				porting_lib_networking: Porting Lib Networking 2.0.547+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.0.547+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.0.547+1.19.2
						porting_lib_extensions: Porting Lib Extensions 2.0.547+1.19.2
							porting_lib_accessors: Porting Lib Accessors 2.0.547+1.19.2
							porting_lib_attributes: Porting Lib Attributes 2.0.547+1.19.2
				porting_lib_tags: Porting Lib Tags 2.0.547+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.0.547+1.19.2
					porting_lib_common: Porting Lib Common 2.0.547+1.19.2
					porting_lib_constants: Porting Lib Constants 2.0.547+1.19.2
		vanityslots: Vanity Slots 1.2.3
		wabi_sabi_structures: Wabi-Sabi Structures 1.1.0
		warriorrage: Warrior Rage 1.19.2-fabric-1.0.1
		wmitaf: WMITAF 3.1.1
		wthit: wthit 5.13.3
		yet-another-config-lib: YetAnotherConfigLib 1.6.0
		yigd: You're in Grave Danger 1.4.5
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.10-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon RX 6750 XT GL version 3.2.0 Core Profile Context 22.11.2.221130, ATI Technologies Inc.
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, loadmyresources.hiddenpack (incompatible)
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Dynamic Crosshair Compat (dynamiccrosshaircompat), Dynamic Crosshair (dynamiccrosshair)

**Comment by jtoo12** [comment]
i fixed it myself
